apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-training-job
spec:
  template:
    metadata:
      name: mnist
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      nodeSelector:
        cloud.google.com/gke-tpu-topology: 2x2  # target topology
        cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice #tpu-v5-lite-podslice
      containers:
      - name: tensorflow
        image: python:3.10 #tensorflow/tensorflow:2.14.0
        securityContext:
          privileged: true
        command:
              - bash
              - -xc
              - |
                pip install https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/tensorflow/tf-2.15.0/tensorflow-2.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
                curl -L https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/libtpu/1.9.0/libtpu.so -o /lib/libtpu.so
                cd /data/tensorflow-mnist-example
                sleep infinity
                ./trainer.sh

                
        #command: ["/bin/bash", "-c", "--"]
        #args: ["cd /data/tensorflow-mnist-example; pip3 install -r requirements.txt; python3 tensorflow_mnist_train_distributed.py"]
                 
        resources:
          requests:
            google.com/tpu: "4"  # TPU chip request
          limits:
            google.com/tpu: "4"  # TPU chip request
        volumeMounts:
        - name: gcs-fuse-csi-vol
          mountPath: /data
          readOnly: false
      serviceAccountName: tpu-sa
      volumes:
      - name: gcs-fuse-csi-vol
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: false
          volumeAttributes:
            bucketName: rick-tpulib-gke
            mountOptions: "implicit-dirs"
      restartPolicy: "Never"
